services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
  
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wahapedia
      POSTGRES_USER: wahapedia
      POSTGRES_PASSWORD: wahapedia
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
